### ISSUE TITLE
Error with .co.il domain

### ISSUE THREAD

**Issue by 20Fourteen** [layershifter/TLDExtract#12]
Hi,

My code is as follows:
`$line = 'http://www.upfile.co.il/xxxxxxxx.html';
$extract = new LayerShifter\TLDExtract\Extract();
		$domain = $extract->parse($line);
		$domain->getRegistrableDomain();`

I get `www.upfile.co.il` instead of `upfile.co.il`.

Any idea what is going wrong?

**Comment by layershifter** [comment]
@20Fourteen I'll check it soon.

**Comment by layershifter** [comment]
@20Fourteen Seems you forget to assign result to variable, you're are using `$domain`, but it's object of `Result` class that has implements `toString`.

----

Here is correct usage:
```php
$extract = new LayerShifter\TLDExtract\Extract();

$result = $extract->parse('http://www.upfile.co.il/xxxxxxxx.html');
$domain = $result->getRegistrableDomain();

var_dump((string)$result, $domain);
```

```php
string(16) "www.upfile.co.il" // output of $result var
string(12) "upfile.co.il" // output of $domain var
```

Don't forget about [parsing modes](https://github.com/layershifter/TLDExtract#parsing-modes).
