### ISSUE TITLE
Parsing .us.com .us.org .eu.org with MODE_ALLOW_ICCAN

### ISSUE THREAD

**Issue by webaddicto** [layershifter/TLDExtract#13]
I need to extract domain names so that example.blogspot.com becomes blogspot.com and so on.

I noticed that some hostnames are not parsed correctly probably, see these examples:

```
profound.eu.org
website.us.org
activia.us.com
```

Using Extract::MODE_ALLOW_ICCAN they are parsed like:

```
LayerShifter\TLDExtract\Result Object
(
    [subdomain:LayerShifter\TLDExtract\Result:private] => activia
    [hostname:LayerShifter\TLDExtract\Result:private] => us
    [suffix:LayerShifter\TLDExtract\Result:private] => com
)
```

But instead I think they should be parsed like:

```
LayerShifter\TLDExtract\Result Object
(
    [subdomain:LayerShifter\TLDExtract\Result:private] => 
    [hostname:LayerShifter\TLDExtract\Result:private] => activia
    [suffix:LayerShifter\TLDExtract\Result:private] => us.com
)
```

I think they should be handled same as example.blogspot.com where example is the subdomain, blogspot is the hostname and com is the suffix (this with MODE_ALLOW_ICCAN of course). Websites with *.us.org and *.us.com can be registered here:

http://us.org/
http://www.us.com/

What are your thoughts?

**Comment by layershifter** [comment]
Hi @webaddicto 

TLDExtract uses TLDDatabase which uses [PublicSuffix List](https://github.com/publicsuffix/list/) as single source of truth. PSL has two sections: ICANN and private domains. So, when you set TLDExtract's parsing mode it operates with determined sections.

`blogspot.com`, `eu.org` is not ICANN domains so they're [defined](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat#L11137) in private section. TLDExtract's result is correct.

However, I understand your problem, my proposal for you is usage of custom database where you'll redefine values for necessary suffixes, see **Custom database** section of README.
