### ISSUE TITLE
IPv6 addresses are not recognized

### ISSUE THREAD

**Issue by supriyo-biswas** [layershifter/TLDExtract#17]
It seems that IPv6 addresses are not recognized properly:

```
>>> $w = new LayerShifter\TLDExtract\Extract()
=> LayerShifter\TLDExtract\Extract {#197}
>>> $res = $w->parse('2bf2:eaa0::7:314:5474')
=> LayerShifter\TLDExtract\Result {#205}
>>> $res->isIp()
=> false
>>> $res->isValidDomain()
=> false
```

**Comment by layershifter** [comment]
@supriyo-biswas IPv6 should be passed in square brackets.

```php
var_dump(tld_extract('[2bf2:eaa0::7:314:5474]')->isIp());
// bool(true)
```

**Comment by supriyo-biswas** [comment]
That kinda defeats the point, isn't it? Recognizing IPv6 addresses natively would allow for verification of domains and IPs from other invalid values in a single step without requiring to pass them through `filter_var()` first.

**Comment by layershifter** [comment]
Current TLDExtract has part of `parse_url` functionality, so when we deal with IPv6 it wants to receive it in square brackets ([RFC 2732](https://www.ietf.org/rfc/rfc2732.txt)).

The next major release will drop this functionality, so you will can pass an IP addresses and domain names, while links will throw an exceptions.
