### ISSUE TITLE
Cache directory is not writable

### ISSUE THREAD

**Issue by NabiKAZ** [layershifter/TLDExtract#2]
Thanks for this extension.

I get this error:
`Cannot put TLD list to cache file /xxxxx/vendor/layershifter/tld-extract/src/../cache/.tld_set, check writes rights on directory of file`

So, I should change permission `cache` directory in `vendor` that this is not good job.

I suggest modify code for check permission and writable with `is_writable()` and if don't have permission, try to change with `chmod()`. or more better solution is auto created `cache` directory with `mkdir('cache', 0777);` command.

**Comment by layershifter** [comment]
Hi, @NabiKAZ 

You use `setCacheFile` method before `parse`. For example:
`Extract::setCacheFile('/path/to/your/dir/cache.file');`
`Extract::setCacheFile(__DIR__ . '/cache/tld.file');`

Is it a solution for your problem?

**Comment by NabiKAZ** [comment]
It's not bad, but I thinks, About a code, all thing must be works well in default. So better is for improve code, check this issue in the code.

**Comment by layershifter** [comment]
Yes, It's reasonable 	proposal. I'll think about it.

**Comment by layershifter** [comment]
Hi, @NabiKAZ 

Part of package that works with database was separated to [TLDDatabase](https://github.com/layershifter/TLDDatabase) package. It's use background update, so it removes much headache :smile: 

TLDDatabase will be used in 1.0 version.
