### ISSUE TITLE
Extract registerable domain returns empty

### ISSUE THREAD

**Issue by Teneobelgium** [layershifter/TLDExtract#21]
I have a loop that extracts registerable domains. However, despite most of them running fine, a still have a lot of empty responses. What could be the cause that it does not find a registerable domain for the following examples : 

mail-sor-f69.google.com  (you would expect google.com)
static.vnpt.vn  (you would expect vnpt.vn)
mx1.sub5.homie.mail.dreamhost.com  (you would expect dreamhost.com)

and there are many , many, many more.

**Comment by layershifter** [comment]
Please provide code that you run.

```php
tld_extract('mail-sor-f69.google.com')->getRegistrableDomain(); // returns 'google.com'
```

**Comment by Teneobelgium** [comment]
Please find below

`		
$ptr = 'mail-sor-f69.google.com';
$tldresult = $extract->parse($ptr);
$tld = $tldresult->getRegistrableDomain();
`

**Comment by layershifter** [comment]
```php
 $extract = new \LayerShifter\TLDExtract\Extract();
 $ptr = 'mail-sor-f69.google.com';
 $tldresult = $extract->parse($ptr);
 $tld = $tldresult->getRegistrableDomain();

 var_dump($tld);
```
```php
  string(10) "google.com"
```

I'm almost sure that there are no problems with package. Try remove `vendors` folder and install depencies again. Also check that you're using latest version of TLDExtract.

Did you touched TLDDatabase? What will return code below?
```php
$store = new \LayerShifter\TLDDatabase\Store();
$store->isExists('com');
$store->isExists('vn');
```
