### ISSUE TITLE
app_dev.php is a valid domain

### ISSUE THREAD

**Issue by Defcon0** [layershifter/TLDExtract#29]
Hello,

would it be possible to add an exception for this special name which is used in the very popular symfony framework?

Bye

**Comment by layershifter** [comment]
Hello,

It seems that you're looking for:
https://github.com/layershifter/TLDExtract#parsing-modes

```php
new Extract(null, null, Extract::MODE_ALLOW_ICANN | Extract::MODE_ALLOW_PRIVATE);
```
