### ISSUE TITLE
Make Extract::suffixExists protected

### ISSUE THREAD

**Issue by Gman98ish** [layershifter/TLDExtract#34]
Currently the `suffixExists` method on the `Extract` class is private, it would be useful if it was protected, so you could override default behavior and provide an alternate data source

**Comment by Rohaq** [comment]
This would be useful; we've got a use case where we need to validate the TLD, but also have a limited list of additional extensions we want to allow for some local domains.

**Comment by layershifter** [comment]
Release in `1.2.7` :v:
