### ISSUE TITLE
Uncaught OutOfRangeException

### ISSUE THREAD

**Issue by jkns** [layershifter/TLDExtract#42]
Hi, I'm getting the error:

```
Stack trace:
Message: Uncaught OutOfRangeException: Unknown field "errors" in xxx/vendor/layershifter/tld-extract/src/Result.php:220
File: xxx/vendor/layershifter/tld-extract/src/Result.php
Line: 220

thrown
#0 LayerShifter\TLDExtract\Result->__get('errors')
```

My code is straight from the example:

```
$extract = new LayerShifter\TLDExtract\Extract();
$result = $extract->parse('shop.github.com');
$result->getRegistrableDomain();
```

Composer install details:

```
Using version ^2.0 for layershifter/tld-extract
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-php72 (v1.10.0): Downloading (100%)         
  - Installing symfony/polyfill-intl-idn (v1.10.0): Downloading (100%)         
  - Installing layershifter/tld-support (1.1.1): Downloading (100%)         
  - Installing layershifter/tld-database (1.0.65): Downloading (100%)         
  - Installing layershifter/tld-extract (2.0.1): Downloading (100%)   
```

Am I missing something or doing something wrong?

Many thanks,

jkns

**Comment by layershifter** [comment]
```php
<?php

include 'vendor/autoload.php';

$extract = new LayerShifter\TLDExtract\Extract();
$result = $extract->parse('shop.github.com');

var_dump(PHP_VERSION, $result->getRegistrableDomain());
```

```
string(5) "7.3.2"
string(10) "github.com"
```

> Am I missing something or doing something wrong?

It seems yes, are you're trying to access `$result->errors`?

**Comment by jkns** [comment]
Ignore. Error was in my code that was already using $result as a variable!!!

**Comment by jkns** [comment]
> ```
> <?php
> 
> include 'vendor/autoload.php';
> 
> $extract = new LayerShifter\TLDExtract\Extract();
> $result = $extract->parse('shop.github.com');
> 
> var_dump(PHP_VERSION, $result->getRegistrableDomain());
> ```
> 
> ```
> string(5) "7.3.2"
> string(10) "github.com"
> ```
> > Am I missing something or doing something wrong?
> 
> It seems yes, are you're trying to access `$result->errors`?

Many thanks for the quick reply, it was an embarrassing mistake that I made. Thanks for this package, good work.
