### ISSUE TITLE
https://youtube.comxyzh is a valid domain

### ISSUE THREAD

**Issue by khavishbhundoo** [layershifter/TLDExtract#44]
Result {#217 ▼
  -subdomain: null
  -hostname: "youtube"
  -suffix: "comxyzh"
}

**Comment by skeets23** [comment]
https://youtube.comxyzh is *not* a valid domain. Are you saying that TLDExtract is incorrectly saying it is a valid domain?

Read the documentation. Non-existent suffixes are allowed by default. To stop allowing them, you have to provide all the options you want (leaving off the non-existing suffix option:

```
$extract = new LayerShifter\TLDExtract\Extract(null, null,\TLDExtract\Extract::MODE_ALLOW_ICANN | LayerShifter\TLDExtract\Extract::MODE_ALLOW_PRIVATE);
$result  = $extract->parse("https://youtube.comxyzh");
$result->isValidDomain();
```

This correctly returns `false`.
