### ISSUE TITLE
Doesn't correctly handle URLs with a "?" just after the domain

### ISSUE THREAD

**Issue by orrd** [layershifter/TLDExtract#5]
For "http://example.com?foo=bar", getRegistrableDomain() returns "example.com?foo=bar" rather than "example.com". 

My temporary quick fix in my code is to replace all "?" characters with "/" before passing the URL to TLDExtract.

**Comment by layershifter** [comment]
Hello, thanks for report. I'll check it soon

**Comment by layershifter** [comment]
I've fixed it in new release, try update to 1.1.1 and check it :smile:

**Comment by orrd** [comment]
Yeah, that seems to be fixed now.
