### ISSUE TITLE
can't find the .tld_set database

### ISSUE THREAD

**Issue by bobflay** [layershifter/TLDExtract#6]
I'm not able to find the the .tld_set database in "/vendor/layershifter/tld_extract/cache folder",
is there  a way to download it?

**Comment by layershifter** [comment]
Hi, @bobflay 

You need [TLDDatabase](https://github.com/layershifter/TLDDatabase), actual database will be in [`resources`](https://github.com/layershifter/TLDDatabase/tree/master/resources) folder of its package. Just note, **TLDDatabase** provides several methods for managing and updating database file.

**Comment by bobflay** [comment]
hello,
` public static function get($url)
    {
        if (self::$cacheFile === null) {
            self::$cacheFile = __DIR__ . '/../cache/.tld_set';
        }`
in this code in Extract.php line 154 you are getting the ```.tld_set``` which is not in the this package anymore

**Comment by layershifter** [comment]
Seems, you're using outdated version, please update to latest, but note, that API was changed.

If you still want use outdated version, you need run once this code:
```php
Extract::setFetch(true);
// or
Extract::updateCache();
```

It might update PSL database.
