### ISSUE TITLE
Get rid of the intl extension requirement

### ISSUE THREAD

**Issue by alexander-schranz** [layershifter/TLDExtract#7]
I use this library inside a symfony project where intl is not required because symfony give a polyfill for it. 

Currently its not possible to use this library without intl installed (composer will error). I would recommend to use the symfony intl polyfill https://github.com/symfony/polyfill-intl-icu instead of require `ext-intl`.

```json
"symfony/polyfill-intl-icu": "^1.0",
```

**Comment by layershifter** [comment]
Here is [detailed](https://github.com/layershifter/TLDExtract/pull/8#issuecomment-260661158) answer "why not". But, I'll work on removal of `ext-intl`.

**Comment by alexander-schranz** [comment]
@layershifter renamed the issue.

**Comment by layershifter** [comment]
@alexander-schranz Thanks for PR and suggestions :+1: 

Released in `1.2.0`.

**Comment by alexander-schranz** [comment]
@layershifter thank you :)
